### ISSUE TITLE
Fishtrap Problems, Salt and Improvements

### ISSUE THREAD

**Issue by Kisutora** [GrowthcraftCE/Growthcraft-1.11#18]
Decided to test the Fishtraps a little more, so this is what I found.

**Test 1**

I set up a 4x2 row of fishtraps on each side with one side having Rotten Flesh in them and the other having nothing. However something seems a little fishy about the results:
![fishtrap_problems1](https://user-images.githubusercontent.com/22685232/28563165-be8ca848-712d-11e7-882f-e2ac78ffefbb.png)
For some reason with this setup two of the rows caught nothing. The ones that caught something seem to be fine. Results of the two rows that caught something:
![fishtrap_problems2](https://user-images.githubusercontent.com/22685232/28563222-fb97fbc0-712d-11e7-90e4-976b1f1f9fe5.png)
I tried removing the Rotten Flesh from the Fishtraps that functioned to see if the rows that caught nothing would start catching fish, but with no success.

**Test 2**

This time I tested a 4x4 area of fishtraps.
The results were quite similar. The row of fishtraps closest to the South of the bunch started filling, while the other traps caught nothing. For this reason I decided to put another row of fishtraps a little further from the 4x4. The single row of fishtraps worked fine and the 4x4 had no change, so I decided to fill the row that worked fine on the 4x4 to see if the other fishing traps would start to catch fish if the row that caught fish before was full. Well, they didn't, so I removed the row completely. Now the closest row to the south started filling, while the other rows caught nothing.
![fishtrap_problems3](https://user-images.githubusercontent.com/22685232/28564323-5065a096-7131-11e7-9d36-fcfdd318d8a1.png)

So something's not quite right here. If you have a row of traps touching each other on the North/South axis only the trap closest to south gets filled, but if you have a row of traps on the West/East axis all traps work fine.
![fishtrap_problems4](https://user-images.githubusercontent.com/22685232/28565541-3d34552c-7135-11e7-88e8-1f7b4804aa47.png)

Traps can be stacked on top of each other and the results are the same. 
![2017-07-25_12 37 36](https://user-images.githubusercontent.com/22685232/28566069-bd06e228-7136-11e7-8f24-749748538219.png)

Fishtraps work with hoppers great now, leaving the bait slot alone! ;>

**The Salt**

Salt Block doesn't currently have a tool that is best used to mine it. (Pickaxe when changed to Rock Salt)
Salt Block drops 9 salt when destroyed. (Should be changed when it's changed to Rock Salt)
Salt needs a different place/destroy sound. (When changed to Rock Salt)

**Comment by Alatyami** [comment]
interesting results .... it is supposed to require Fluid on N, NE, E, SE, S, SW, W, and NW before fishing. Until we work out a bait system, any bait switches to the Loot Table for FISHING.FISH.
