### ISSUE TITLE
Request add my modpack Curse (HippyCraft)

### ISSUE THREAD

**Issue by roulito** [GrowthcraftCE/Growthcraft-1.11#20]
I would like to be able to add your mod to my modpack (Hippycraft on Curse) since you did not put the version 3.0.0.2 compatible Mc 1.11.2 on Curse I have to ask for an approval to put it on my modpack and Provide it to Curse. Or possibly upload last version on Curse

**Comment by Alatyami** [comment]
The 3.0.0.x series probably will not be added to curse until around 3.0.0.5 once we hit the cellar mod. You are approved for including Growthcraft 3.x.x.x with Hippycraft. 

![approved](https://user-images.githubusercontent.com/1868411/28753792-d619e114-7507-11e7-92fd-75271916b259.gif)
