### ISSUE TITLE
Mod Pack request w/mod list

### ISSUE THREAD

**Issue by GameIntell** [GrowthcraftCE/Growthcraft-1.11#41]
Hello, I would like to use this mod in my mod pack called: "Augmented Triad"

As requested per your license, here are the mods that are going to be used in it:

bspkersCore
Baubles
CodeChickenLib
ForgeMultipart
Forge
ArmorStatusHUD
StatusEffectHUD
Ars Magica 2
4Space
AE2 Stuff
Ancient Warfare 2
AnimationAPI
Another One Bites the Dust
AppleCore
Applied Energistics 2
Automagy
BdLib
Big Reactors
Biomes O Plenty
Botania
Buildcraft
Buildcraft compat
Carpenters blocks
Chisel
Chisel Tones
CodeChickenCore
CoFH Core
ComputerCraft
Damage Indicators Mod
Decocraft
Dense ores
Ender Core
Ender IO
ExtraCells
ExtraTiC
Extra Utilities
Forbidden Magic
Forestry
Galacticraft Planets
Galacticraft Core
Growthcraft Community edition
HardcoreEnderExpansion
HQM The Journey
Hunger Overhaul
Iguana Tinker Tweaks
Inventory Tweaks
Jabba
JourneyMap
LunatriusCore
Mantle
MatterOverdrive
Minecraft Comes Alive
Mekanisim
Mekanisim Tools
Mekanisim Generators
MicdoodleCore
Minefactory reloaded
Minetweaker3
MouseTweaks
Natura
NEIaddons
NEI Intergration
Nether Ores
NotEnoughItems
Not Enough Keys
not enough resources
Open Blocks
OpenEye
Pams Harvestcraft
Radix Core
Railcraft
RandomThings
Refined Relocation
Schematica
tcnodetracker
TConstruct
Technomancy
Thaumcraft
Thaumcraftneiplugin
Thaumicenergistics
Thaumic Tinkerer
Thermal Dynamics
Thermal Expansion
Thermal Foundation
TiCTooltips
TMechworks
Twilight Forest
VeinMiner
Waila
Waila Harvestability
WAILAPlugins
Wawla
Witchery
Ztones

**Comment by Alatyami** [comment]
Approved. Thanks!  Let us know if you find any bugs. We have a Discord channel as well if you want to ask of a bug has been reported yet.
