### ISSUE TITLE
Move the Culture Jar from GC-Cellar to GC-Milk

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.11#49]
It makes more sense to have the culture jar in GCMilk as it is the only module that uses it.

**Comment by IceDragon200** [comment]
Actually you could place fruit juices into the culture jar along with... something, I forget what produces yeast (I think you put yeast in it? yeast + juice = more yeast)

But that was the reason it was moved to cellar in 2.7

**Comment by Alatyami** [comment]
Ah, that makes sense .... back to Cellar you go !
