### ISSUE TITLE
Culture Jar render glitches

### ISSUE THREAD

**Issue by Avatair** [GrowthcraftCE/Growthcraft-1.11#63]
A render glitch occures when approaching a placed Culture Jar:
![culture-jar-issue4](https://user-images.githubusercontent.com/21110130/35195496-c05ebdd0-fec4-11e7-8be9-832ea318cc79.png)

Possible issue is the BlockRenderLayer.TRANSLUCENT render layer of the jar block.

**Comment by Kisutora** [comment]
Model has been changed, no further issues. Closing issue.
