### ISSUE TITLE
Cheese wheel textures

### ISSUE THREAD

**Issue by Avatair** [GrowthcraftCE/Growthcraft-1.11#64]
A set of textures for cheese is needed.

For all ageable, but not waxed types (Gorgonzola=0, Emmentaler=1, Appenzeller=2, Asiago=3, Parmesan=4):
- Stage "unaged": outside_top
- Stage "unaged": outside_bottom
- Stage "unaged": outside_sides
- Stage "aged": outside_top
- Stage "aged": outside_bottom
- Stage "aged": outside_sides
- Stage "cut": inside

For all waxable types (Cheddar=0, Monterey=1):
- Stage "unaged and unwaxed": outside_top
- Stage "unaged and unwaxed": outside_bottom
- Stage "unaged and unwaxed": outside_sides
- Stage "waxed": outside_top
- Stage "waxed": outside_bottom
- Stage "waxed": outside_sides
- Stage "cut": inside

As information, unaged and unwaxed cheeses can't be cutted.

**Comment by Kisutora** [comment]
Closing issue since there is an updated version of this issue with item textures as well: https://github.com/GrowthcraftCE/Growthcraft-1.11/issues/99
