### ISSUE TITLE
Reuseable cheese cloth

### ISSUE THREAD

**Issue by Avatair** [GrowthcraftCE/Growthcraft-1.11#65]
A possibility to reuse the cheese cloth, after retrieving cheese wheel from press.

The reason is, that the cloth is made of 8 strings, which might be expensive. Would it be an option to introduce a reusage limit to a fixed amount of 3 times?

**Comment by Alatyami** [comment]
We should be able to give it a damage level. But you are right, 8 string can be hard to come by.

**Comment by Avatair** [comment]
There is a restriction in the amount of storage bits. It must be some small number of usages, because it will be stored along the cheese type itself in the item meta of hanging curds. But 8 is good enough as it takes only 3 bits.

**Comment by IceDragon200** [comment]
You could encode the usage amount in the NBT data, or instead just have the cheese cloth recipe produce multiple cheese cloths instead, no need to complicate things

8 strings for 4 cheese cloths maybe

**Comment by Alatyami** [comment]
@IceDragon200 , you bring up a good point. We could simply just increase the number of cheese cloth produced and then let it be consumed in the end. I'm liking that suggestion. Makes it simple and linear.

**Comment by Avatair** [comment]
Okay then. We can change the crafting recipe output to lower the costs.
