### ISSUE TITLE
Model for cheese press

### ISSUE THREAD

**Issue by Avatair** [GrowthcraftCE/Growthcraft-1.11#67]
A model for cheese press is required.

**Comment by Alatyami** [comment]
Two block high model like the Fruit Press but with a cork screw at the top. We could actually reuse the fruit press base.

**Comment by IceDragon200** [comment]
The cheese press has a circular base though, unless you intend to cheese the cheese wheel to a cheese block?

**Comment by Alatyami** [comment]
Ah, good call. No cheese blocks here :)

**Comment by Avatair** [comment]
I would prefer to use one block high model in order to avoid animations crossing boundary between two blocks. As the cheese block is only 8px heigh, I think the other 8px for the base, cap and screw would be enough. Do you agree?

**Comment by Alatyami** [comment]
That'll work, we can keep it as one block. I have an idea ... I'll draft it in blockbench and post it.

**Comment by Avatair** [comment]
Model has been finished. Shall we leave the issue open?

**Comment by Alatyami** [comment]
It'll get closed after release?

**Comment by Avatair** [comment]
I move the ticket to Pending Releases instead then, to track it as finished.
