### ISSUE TITLE
New butter churn

### ISSUE THREAD

**Issue by Avatair** [GrowthcraftCE/Growthcraft-1.11#68]
A suggestion was made to have a bigger butter churn spanning over two blocks:

Concept 1:
![churn_concept_two_block](https://user-images.githubusercontent.com/21110130/35455647-0bcbcefe-02d3-11e8-8d3f-85c44a0c4fbd.png)

Concept 2:
![4ec924588480eea5509704993d37d57d](https://user-images.githubusercontent.com/21110130/35456162-e35429ce-02d4-11e8-88ee-5eff8a0333d2.png)

Shall the butter churn be changed?

**Comment by Alatyami** [comment]
Going to go with the second image.
