### ISSUE TITLE
Pancheon goes over the inventory slot bounding box.

### ISSUE THREAD

**Issue by Kisutora** [GrowthcraftCE/Growthcraft-1.11#69]
![2018-01-27_14 58 46](https://user-images.githubusercontent.com/22685232/35472228-e2d832e8-0373-11e8-8d5b-3f6029bcad30.png)

**Comment by Avatair** [comment]
Can be fixed, by adjust the display.gui.scale parameter in pancheon.json

**Comment by Kisutora** [comment]
Fixed!
