### ISSUE TITLE
Implement different grape plant types

### ISSUE THREAD

**Issue by Avatair** [GrowthcraftCE/Growthcraft-1.11#70]
In GC there are three grape types supported, which are growing on one plant type. The decision is, whether we can have three plant types instead?

An advantage of having separate plant types is that the farming will be faster when growing one sort, because the player can decide to grow only one specific plant type. In the current implementation the plant would yield only 1/3 of the amount of desired grape type.

**Comment by Kisutora** [comment]
Yes.

**Comment by Avatair** [comment]
Implemented.
