### ISSUE TITLE
Pancheon is being held in a weird angle in first person mode

### ISSUE THREAD

**Issue by Kisutora** [GrowthcraftCE/Growthcraft-1.11#74]
![2018-01-28_11 20 55](https://user-images.githubusercontent.com/22685232/35480749-cd5bd334-041d-11e8-8944-869362b096e8.png)

Third person mode is fine though:
![2018-01-28_11 21 16](https://user-images.githubusercontent.com/22685232/35480751-d87b56a4-041d-11e8-8be3-0adc771c9e6a.png)

**Comment by Avatair** [comment]
Rotation can be adjusted in the json model file of the pancheon.

**Comment by Kisutora** [comment]
Fixed!
