### ISSUE TITLE
Fishtrap catches fish when there is no water + Problems with Harvestcraft

### ISSUE THREAD

**Issue by Kisutora** [GrowthcraftCE/Growthcraft-1.11#8]
So apparently fish can fly nowadays. Fishtrap started filling up while I was editing the GUI textures. :D
![fishtrap_airfish](https://user-images.githubusercontent.com/22685232/28438959-a549c29a-6da8-11e7-9005-78c5d7daf82a.png)
![fishtrap_nowater](https://user-images.githubusercontent.com/22685232/28438958-a54680a8-6da8-11e7-80ee-3bc2b73a9908.png)
Seems a bit broken.

As Growthcraft 1.11 Alpha 3.0.0.1 came out I decided to leave a few fishtraps underwater while I went to have some breakfast and when I got back to it these were the results: ![sample 1](https://user-images.githubusercontent.com/22685232/28403781-f5c9db9e-6d2e-11e7-9116-1e93852d4e81.png)
![sample 2](https://user-images.githubusercontent.com/22685232/28403782-f5ca7950-6d2e-11e7-94d4-6127ee5b376e.png)
 As you can see with Harvestcraft installed the Fishtraps fill up very quickly if you're going the manual route. This overflow of fish can be dealt with by building an automatic hopper chest system![automatic farm](https://user-images.githubusercontent.com/22685232/28403779-f5c822fe-6d2e-11e7-9318-a63c2c93efd9.png) so I thought I'd just let you know that this is a thing and it could possibly be annoying for players that don't want an automatic fish farm and have Harvestcraft installed. For me however and probably for most players you'll be building an automatic farm anyways so I don't see this as a problem. **What is a problem however is Harvestcraft fish going into the item slot reserved for rotten flesh.** Thanks!

P.S. The fishtrap appears transparent when you hold the block in your hand but when you place it it's not transparent.
![fishtrap transparency](https://user-images.githubusercontent.com/22685232/28403778-f5c814b2-6d2e-11e7-83bd-c6f0e8ce2627.png)
![manual farm](https://user-images.githubusercontent.com/22685232/28403780-f5c9686c-6d2e-11e7-96c1-262bf7486b34.png)

**Comment by Alatyami** [comment]
Thank you for being an early tester. Due to your feedback we have resolve with the next release.

Fix: c119624a6da7fb10c05c3756af987d757be5fdda

**Comment by Kisutora** [comment]
Awesome! I'll be sure to report any future bugs I encounter as the mod grows, cheers!

**Comment by Alatyami** [comment]
Released fix with 3.0.0.1-1
